ttb_controller:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

  gazebo_ros_control:
    pid_gains:
      joint_1: {p: 100, i: 0.1, d: 10}
      joint_2: {p: 100, i: 0.1, d: 10}
      joint_3: {p: 100, i: 0.1, d: 10}
      joint_4: {p: 100, i: 0.1, d: 10}
      joint_5: {p: 100, i: 0.1, d: 10}
      joint_6: {p: 100, i: 0.1, d: 10}
controller_list:
  - name: ttb_controller/position_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    allowed_execution_duration_scaling: 1.2
    allowed_goal_duration_margin: 0.5