controller_list:
  - name: fake_Arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_End_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_7
initial:  # Define initial robot poses per group
  - group: Arm
    pose: home